baseURL = 'http://fast-hep.github.io/'
languageCode = 'en-us'
title = 'FAST-HEP'
enableEmoji = true
# theme = "hugo-geekdoc"
theme = "scientific-python-hugo-theme"

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Required if you want to render robots.txt template
enableRobotsTXT = true

disableKinds = ["taxonomy"]

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[taxonomies]
   tag = "tags"

[params]
[params.author]
name = "FAST-HEP"

[[params.navbar]]
title = "Getting started"
url = "/getting-started/"

[[params.navbar]]
title = "Concepts"
url = "/concepts/"

[[params.navbar]]
title = "Packages"
url = "/packages/"

[[params.navbar]]
title = "Tutorials"
url = "/tutorials/"

[[params.navbar]]
title = "Talks"
url = "/talks/"

[[params.navbar]]
title = "Contributing"

[params.footer]
logo = "logo.svg"
socialmediatitle = "FAST-HEP"

[[params.footer.socialmedia]]
link = "https://github.com/FAST-HEP"
icon = "github"

[[params.footer.socialmedia]]
link = "https://github.com/FAST-HEP/fasthep/discussions"
icon = "discourse"

[params.footer.quicklinks]

  [params.footer.quicklinks.column1]
  title = "Project"

  [[params.footer.quicklinks.column1.links]]
  text = "GitHub organisation"
  link = "https://github.com/FAST-HEP"

  [[params.footer.quicklinks.column1.links]]
  text = "fasthep meta package"
  link = "https://github.com/FAST-HEP/fasthep"

  [[params.footer.quicklinks.column1.links]]
  text = "Discussions"
  link = "https://github.com/FAST-HEP/fasthep/discussions"

  [params.footer.quicklinks.column2]
  title = "Documentation"

  [[params.footer.quicklinks.column2.links]]
  text = "Workflow concepts"
  link = "/concepts/"

  [[params.footer.quicklinks.column2.links]]
  text = "Packages"
  link = "/packages/"

  [[params.footer.quicklinks.column2.links]]
  text = "Tutorials"
  link = "/tutorials/"

  [params.footer.quicklinks.column3]
  title = "Packages"

  [[params.footer.quicklinks.column3.links]]
  text = "fasthep-flow"
  link = "https://github.com/FAST-HEP/fasthep-flow"

  [[params.footer.quicklinks.column3.links]]
  text = "fasthep-carpenter"
  link = "https://github.com/FAST-HEP/fasthep-carpenter"

  [[params.footer.quicklinks.column3.links]]
  text = "fasthep-curator"
  link = "https://github.com/FAST-HEP/fasthep-curator"