baseURL = "https://fast-hep.github.io/"
locale = "en-US"
title = "FAST-HEP"

theme = "scientific-python-hugo-theme"

enableEmoji = true
enableRobotsTXT = true
pluralizeListTitles = false
disablePathToLower = true

disableKinds = ["taxonomy", "term"]

[markup]
defaultMarkdownHandler = "goldmark"

  [markup.goldmark.renderer]
  unsafe = true

  [markup.tableOfContents]
  startLevel = 2
  endLevel = 4

[params]
custom_css = ["css/custom.css"]
sidebar = true

[params.navbarlogo]
image = "fast-hep-black.png"
link = "/"

[params.author]
name = "FAST-HEP"

[[params.navbar]]
title = "Getting started"
url = "/getting-started/"

[[params.navbar]]
title = "Concepts"
url = "/concepts/"

[[params.navbar]]
title = "Packages"
url = "/packages/"

[[params.navbar]]
title = "Tutorials"
url = "/tutorials/"

[[params.navbar]]
title = "Contributing"
url = "/contributing/"

[params.footer]
logo = "fast-hep-black-squareBkg.png"
socialmediatitle = "FAST-HEP"

[[params.footer.socialmedia]]
link = "https://github.com/FAST-HEP"
icon = "github"

[[params.footer.socialmedia]]
link = "https://github.com/FAST-HEP/fasthep/discussions"
icon = "discourse"

[params.footer.quicklinks]

  [params.footer.quicklinks.column1]
  title = "Project"

  [[params.footer.quicklinks.column1.links]]
  text = "GitHub organisation"
  link = "https://github.com/FAST-HEP"

  [[params.footer.quicklinks.column1.links]]
  text = "fasthep meta package"
  link = "https://github.com/FAST-HEP/fasthep"

  [[params.footer.quicklinks.column1.links]]
  text = "Discussions"
  link = "https://github.com/FAST-HEP/fasthep/discussions"

  [params.footer.quicklinks.column2]
  title = "Documentation"

  [[params.footer.quicklinks.column2.links]]
  text = "Getting started"
  link = "/getting-started/"

  [[params.footer.quicklinks.column2.links]]
  text = "Concepts"
  link = "/concepts/"

  [[params.footer.quicklinks.column2.links]]
  text = "Packages"
  link = "/packages/"

  [[params.footer.quicklinks.column2.links]]
  text = "Tutorials"
  link = "/tutorials/"

  [params.footer.quicklinks.column3]
  title = "Resources"

  [[params.footer.quicklinks.column3.links]]
  text = "Workshop"
  link = "https://fasthep-workshop.readthedocs.io/en/latest/"

  [[params.footer.quicklinks.column3.links]]
  text = "Flow documentation"
  link = "https://fasthep-flow.readthedocs.io/en/latest/"

  [[params.footer.quicklinks.column3.links]]
  text = "Contributing"
  link = "https://github.com/FAST-HEP/fasthep/blob/main/CONTRIBUTING.md"
